### ISSUE TITLE
⏸️[FEATURE REQUEST]🦄USB serial support on  ESP32-S2/ESP32-S3 for systems using  CP210x, FTDI FT23x or CP34x

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP8266#851]
Idf 5.1 has recently implemented multiple drivers registration support for USB CDC-ACM Virtual Com , it is implemented in [ESP3D-TFT project](https://github.com/luc-github/ESP3D-TFT/discussions/1#discussioncomment-4712100)

I have tested the feature with ESP3D-TFT and several boards (end3/ ender5/ FYSTEC E4, ESP32 boards...) and so far so good, but the esp board still need external power supply because USB port do not power esp,  but no need to find serial port connections on printer/cnc anymore, just use right cable to connect printer/cnc USB port to ESP32-S2/S3 and they can communicate, this long time request finally come true ^_^  

Arduino core dev team is working on IDF 5.1 implementation - https://github.com/espressif/arduino-esp32/blob/esp-idf-v5.1/
Once merged / released I will port ESP3D to this version and implement the USB-OTG support on ESP32-S2 and ESP32-S3.

**Comment by liqijian101** [comment]
It is wonderful！！I'm looking forward to this function

**Comment by khayamgondal** [comment]
@luc-github any update on this? Did you merge in ?

**Comment by luc-github** [comment]
no, core 3.0 is.not released

**Comment by luc-github** [comment]
Working on porting USB-OTG from ESP3D-TFT to a ESP3D I have realized that IDF 5.1.2 release updated the USB drivers
before:
```
## IDF Component Manager Manifest File
dependencies:
  usb_host_ch34x_vcp: "^1"
  usb_host_cp210x_vcp: "^1"
  usb_host_ftdi_vcp: "^1"
  usb_host_vcp: "^1"
  idf: ">=5.1.0"
```

to 
```
## IDF Component Manager Manifest File
dependencies:
  usb_host_ch34x_vcp: "^2"
  usb_host_cp210x_vcp: "^2"
  usb_host_ftdi_vcp: "^2"
  usb_host_vcp: "^1"
  idf: ">=5.1.0"
```
which bring some minor API change  but also a RX buffer  with configurable size

![image](https://github.com/luc-github/ESP3D-TFT/assets/8822552/ee4c6899-08ae-4f7a-9fd6-0af3ef38925f)

So I will update the code to handle driver update in ESP3D-TFT first and review the porting code I have already did which consist in an additional arduino library using idf usb-otg component
